services:
  postgres_db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_DEV}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB_DEV}"]
      interval: 5s
      retries: 5

volumes:
  db-data:
