default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>
  username: <%= ENV.fetch("PG_USER") { "postgres" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: <%= ENV.fetch("PG_DB_DEV") { "db_dev" } %>

test:
  <<: *default
  database: <%= ENV.fetch("PG_DB_TEST") { "db_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("PG_DB_PROD") { "db_production" } %>
